-- CREATE DATABASE IF NOT EXISTS `hashsnapdb`;
-- GRANT ALL PRIVILEGES ON hashsnapdb.* TO 'ohgiraffers'@'%';

DROP TABLE IF EXISTS tbl_user;

CREATE TABLE IF NOT EXISTS tbl_user
(
	`USER_CODE`  INT PRIMARY KEY AUTO_INCREMENT,
    `NICKNAME`    VARCHAR(20)  NOT NULL COMMENT '아이디',
    `PASSWORD`   VARCHAR(255) NOT NULL COMMENT '비밀번호',
    `USER_NAME`  VARCHAR(255) NOT NULL COMMENT '이름',
    `USER_PHONE` VARCHAR(20)  NOT NULL COMMENT '전화번호',
    `USER_EMAIL`   VARCHAR(50) NULL COMMENT '이메일',
     `USER_ROLE`  VARCHAR(10) NOT NULL COMMENT '역할/권한'
);
